/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as StarwarsImport } from "./routes/starwars";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const StarwarsRoute = StarwarsImport.update({
  id: "/starwars",
  path: "/starwars",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/starwars": {
      id: "/starwars";
      path: "/starwars";
      fullPath: "/starwars";
      preLoaderRoute: typeof StarwarsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/starwars": typeof StarwarsRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/starwars": typeof StarwarsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/starwars": typeof StarwarsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/starwars";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/starwars";
  id: "__root__" | "/" | "/starwars";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  StarwarsRoute: typeof StarwarsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StarwarsRoute: StarwarsRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/starwars"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/starwars": {
      "filePath": "starwars.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
